# Title for the workflow as displayed in the GitHub Actions UI
name: Playwright Tests

on:
  # Run the workflow when code is pushed to the main or master branches
  push:
    branches:
      - main
      - master
  # Also run the workflow for pull requests targeting main or master
  pull_request:
    branches:
      - main
      - master

jobs:
  test:
    # Job name shown in the UI
    name: Run Playwright
    # Use the latest Ubuntu runner provided by GitHub
    runs-on: ubuntu-latest

    steps:
      # Fetch the repository contents so the workflow can access the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Install the requested Node.js version and enable npm caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      # Install project dependencies from package-lock.json
      - name: Install dependencies
        run: npm ci

      # Install the Playwright browser binaries and system dependencies
      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      # Execute the Playwright end-to-end test suite
      - name: Run Playwright tests
        run: npx playwright test

      # Upload the Playwright HTML report even if tests fail
      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          # Name the uploaded artifact for easy identification
          name: playwright-report
          # Point to the directory containing the generated report
          path: playwright-report
          # Do not fail the workflow if the report directory is missing
          if-no-files-found: ignore



